# --- !Ups
create table OUTGOING_EMAIL (
  ID uuid not null,
  CREATED_UTC timestamp(3) not null,
  EMAIL text,
  RECIPIENT varchar(255),
  RECIPIENT_EMAIL varchar(1000),
  SENT_AT_UTC timestamp(3),
  LAST_SEND_ATTEMPT_AT_UTC timestamp(3),
  FAILURE_REASON text,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_USER VARCHAR(100) NULL,
  constraint PK_OUTGOING_EMAIL primary key (ID)
);

create index IDX_OUTGOING_EMAIL_SENT_AT_RECIPIENT on OUTGOING_EMAIL (SENT_AT_UTC DESC, RECIPIENT_EMAIL);

create table OUTGOING_EMAIL_VERSION (
  ID uuid not null,
  CREATED_UTC timestamp(3) not null,
  EMAIL text,
  RECIPIENT varchar(255),
  RECIPIENT_EMAIL varchar(1000),
  SENT_AT_UTC timestamp(3),
  LAST_SEND_ATTEMPT_AT_UTC timestamp(3),
  FAILURE_REASON text,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  VERSION_USER VARCHAR(100) NULL,
  CONSTRAINT PK_OUTGOING_EMAIL_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_OUTGOING_EMAIL_VERSION ON OUTGOING_EMAIL_VERSION (ID, VERSION_UTC);

# --- !Downs

DROP TABLE OUTGOING_EMAIL;
DROP TABLE OUTGOING_EMAIL_VERSION;
