# --- !Ups
CREATE TABLE UPLOADED_FILE (
  ID uuid NOT NULL,
  FILE_NAME varchar NOT NULL,
  CONTENT_LENGTH bigint NOT NULL,
  CONTENT_TYPE varchar NOT NULL,
  UPLOADED_BY varchar NOT NULL,
  OWNER_ID uuid,
  OWNER_TYPE varchar,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_USER varchar,
  CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (ID)
);

CREATE INDEX IDX_UPLOADED_FILE_OWNER ON UPLOADED_FILE (OWNER_ID, OWNER_TYPE);

CREATE TABLE UPLOADED_FILE_VERSION (
  ID uuid NOT NULL,
  FILE_NAME varchar NOT NULL,
  CONTENT_LENGTH bigint NOT NULL,
  CONTENT_TYPE varchar NOT NULL,
  UPLOADED_BY varchar NOT NULL,
  OWNER_ID uuid,
  OWNER_TYPE varchar,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  VERSION_USER varchar,
  CONSTRAINT PK_UPLOADED_FILE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_UPLOADED_FILE_VERSION ON UPLOADED_FILE_VERSION (ID, VERSION_UTC);

# --- !Downs
DROP TABLE UPLOADED_FILE_VERSION;
DROP TABLE UPLOADED_FILE;