# Use container-based infrastructure
sudo: false

language: scala

jdk: openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test integration/test

node_js: "10"

before_script:
  - npm i -g npm
  - npm ci

scala:
  - 2.13.1

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
